from enum import Enum

class MaintenanceType(str, Enum):
    OIL_CHANGE = "OIL_CHANGE"
    TIRE_ROTATION = "TIRE_ROTATION"
    BRAKE_INSPECTION = "BRAKE_INSPECTION"
    BATTERY_CHECK = "BATTERY_CHECK"
    ENGINE_TUNE_UP = "ENGINE_TUNE_UP"
    ROUTINE_SERVICE = "ROUTINE_SERVICE"
    TIRES = "TIRES"
    BRAKES = "BRAKES"
    BATTERY = "BATTERY"
    ENGINE = "ENGINE"
    TRANSMISSION = "TRANSMISSION"
    ELECTRICAL = "ELECTRICAL"
    AC_HEATING = "AC_HEATING"
    INSPECTION = "INSPECTION"
    REPAIR = "REPAIR"
    OTHER = "OTHER"
